# /// script
# requires-python = ">=3.11"
# dependencies = [
#   "requests",
# ]
# ///

"""
entra_setup.py — Provision Microsoft Entra ID resources for the real-IdP harness.
==================================================================================

Uses the ``kdbai-service-mcp-agent`` app registration to configure itself and
provision all supporting resources. The same app registration serves two roles:

  1. During setup: authenticates against the Graph API to provision resources.
     Requires broad Graph permissions (see Prerequisites) which can be removed
     from the app registration once provisioning is complete.

  2. At runtime: the app the MCP container validates tokens against.
     Users authenticate against this app registration to obtain JWTs.

Configures the following on the kdbai-service-mcp-agent app registration:
  - Service Principal     (required for token issuance and sign-in)
  - API Scope             (sets aud claim to api://<client-id>)
  - Access token version  (sets requestedAccessTokenVersion=2, required by FastMCP's AzureProvider)
  - Redirect URI          (Web platform callback used by FastMCP's AzureProvider)
  - Client secret         (auto-generated if absent; written to .env.entra)
  - Groups claim          (emits group Object IDs in access tokens, off by default)
  - Public client flows   (enables ROPC password grant; off by default in Entra,
                           fixed up on every run — not just at creation — so an
                           app registration created manually in the portal is
                           also covered)
  - Token Lifetime Policy (attached to the service principal)

Provisions the following directory resources:
  - Security Groups       (one per group per namespace, prefixed with namespace name)
  - Users                 (with passwords, no forced reset on first sign-in)
  - Group memberships     (as defined in the config)

Output:
  Writes the provisioned values (tenant/client IDs, group Object IDs, domain,
  ENTRA_APP_ID_URI, KX_MCP_AUTH_* inbound-validation vars) to
  ``tests/deterministic/realidp/envs/.env.entra`` in ``export VAR=value`` form —
  the format sourced by ``just test-entra``.

  The script reads *inputs* from the environment (tenant/client/secret + passwords)
  and writes the full live ``.env.entra`` (provisioned outputs + preserved inputs).
  It does NOT copy ``.env.entra.example`` — that is a first-time-only README step.
  Re-running the script is safe: all Graph operations are idempotent and existing
  inputs are preserved from ``os.environ`` first, then the existing file.

  User passwords are NEVER written; they must be injected manually or as masked CI
  variables. The client secret IS written since it is generated by this script and
  only retrievable once, at creation time.

  The output file is gitignored. Do NOT commit it.

Prerequisites
-------------
1. Create the ``kdbai-service-mcp-agent`` App Registration in Entra ID and assign
   the following Microsoft Graph *application* permissions, all admin-consented:
     - Application.ReadWrite.All
     - Group.ReadWrite.All
     - User.ReadWrite.All
     - Policy.ReadWrite.ApplicationConfiguration
     - Policy.Read.All
     - Organization.Read.All

   These permissions are only needed to run this script. They can be removed
   from the app registration once provisioning is complete.

2. Set env vars (do not hardcode secrets). You can source your partially-filled
   .env.entra or export them directly:
     export ENTRA_TENANT_ID="<Directory ID from the app registration Overview>"
     export ENTRA_CLIENT_ID="<Application ID from the app registration Overview>"
     export ENTRA_CLIENT_SECRET="<Secret Value>"
     export ENTRA_PASSWORD_ROOT="<password for root user>"
     export ENTRA_PASSWORD_ALICE="<password for alice user>"
     export ENTRA_PASSWORD_BOB="<password for bob user>"
     # Optional — second tenant for charlie / wrong-issuer persona (test 2.41):
     export ENTRA_PASSWORD_CHARLIE="<password for charlie user>"

3. Optionally set:
     export ENTRA_REDIRECT_URI="http://localhost:8000/auth/callback"

4. Run from the repo root:
     uv run python tests/deterministic/realidp/setup/entra/entra_setup.py

The script is fully idempotent. It can be re-run safely without creating duplicate
resources. Existing resources are detected and skipped.
"""

import json
import os
import sys
import time
import uuid
from pathlib import Path

import requests

# ---------------------------------------------------------------------------
# Configuration — all values from environment (no hardcoded secrets)
# ---------------------------------------------------------------------------

ENTRA_CONFIG = {
    "tenant_id":     os.environ.get("ENTRA_TENANT_ID", ""),
    "client_id":     os.environ.get("ENTRA_CLIENT_ID", ""),
    "client_secret": os.environ.get("ENTRA_CLIENT_SECRET", ""),
}

ENTRA_APP_NAME = "kdbai-service-mcp-agent"

# Redirect URI FastMCP's AzureProvider expects for the OAuth callback.
# Override via ENTRA_REDIRECT_URI if your test server uses a different host/port/path.
ENTRA_REDIRECT_URI = os.environ.get("ENTRA_REDIRECT_URI", "http://localhost:8000/auth/callback")

# Display name used for the auto-generated client secret. Re-running the script will
# not regenerate a secret with this exact name if one already exists (see ensure_client_secret).
ENTRA_SECRET_DISPLAY_NAME = "fastmcp-auto-generated"

# Persona / group structure — mirrors the Keycloak config so the two IdPs
# back the same test personas (see idp/personas.yaml).
_PERSONA_CONFIG = {
    "client": {
        "client_id": ENTRA_APP_NAME,
        "public_client": True,
    },
    "namespaces": {
        "quants": {
            "token_settings": {"access_token_lifespan_seconds": 900},
            "groups": ["admin", "trader", "viewer"],
            "users": [
                {"username": "alice", "password_env": "ENTRA_PASSWORD_ALICE", "groups": ["viewer", "trader"]},
                {"username": "bob",   "password_env": "ENTRA_PASSWORD_BOB",   "groups": ["viewer"]},
            ],
        },
        "risk": {
            "token_settings": {"access_token_lifespan_seconds": 900},
            "groups": ["admin", "viewer"],
            "users": [
                # charlie belongs in the second tenant (ENTRA_TENANT_ID_RISK).
                # This script runs against the primary tenant only — skipped below when
                # ENTRA_TENANT_ID_RISK is unset. second_tenant=True scopes that skip to
                # charlie only, so a merely-missing password for any other user still
                # fails loudly via _resolve_password instead of being silently skipped.
                {"username": "charlie", "password_env": "ENTRA_PASSWORD_CHARLIE", "groups": ["viewer"],
                 "second_tenant": True},
            ],
        },
        "manager": {
            "token_settings": {"access_token_lifespan_seconds": 900},
            "groups": ["admin"],
            "users": [
                {"username": "root", "password_env": "ENTRA_PASSWORD_ROOT", "groups": ["admin"]},
            ],
        },
    },
}

GRAPH_BASE = "https://graph.microsoft.com/v1.0"

# ---------------------------------------------------------------------------
# Authentication
# ---------------------------------------------------------------------------


def get_access_token() -> str:
    """Obtain a bearer token using the OAuth2 client credentials flow."""
    missing = [k for k, v in ENTRA_CONFIG.items() if not v]
    if missing:
        for key in missing:
            print(f"ERROR: ENTRA_{key.upper()} environment variable not set.")
        sys.exit(1)

    url = f"https://login.microsoftonline.com/{ENTRA_CONFIG['tenant_id']}/oauth2/v2.0/token"
    resp = requests.post(url, data={
        "grant_type":    "client_credentials",
        "client_id":     ENTRA_CONFIG["client_id"].strip(),
        "client_secret": ENTRA_CONFIG["client_secret"],
        "scope":         "https://graph.microsoft.com/.default",
    })
    if resp.status_code != 200:
        print(f"ERROR: Authentication failed ({resp.status_code}): {resp.text}")
        print("  Check ENTRA_CLIENT_SECRET is the secret Value (not a password),")
        print("  and that the app has the required Application permissions with admin consent.")
        sys.exit(1)
    return resp.json()["access_token"]


def graph_headers(token: str) -> dict:
    return {"Authorization": f"Bearer {token}", "Content-Type": "application/json"}


# ---------------------------------------------------------------------------
# Graph API helpers
# ---------------------------------------------------------------------------


def get(token: str, path: str) -> dict:
    r = requests.get(f"{GRAPH_BASE}{path}", headers=graph_headers(token))
    r.raise_for_status()
    return r.json()


def post(token: str, path: str, body: dict) -> dict:
    r = requests.post(f"{GRAPH_BASE}{path}", headers=graph_headers(token), json=body)
    if not r.ok:
        print(f"  [error] POST {path} → {r.status_code}: {r.text}")
    r.raise_for_status()
    return r.json() if r.content else {}


def patch(token: str, path: str, body: dict) -> None:
    r = requests.patch(f"{GRAPH_BASE}{path}", headers=graph_headers(token), json=body)
    r.raise_for_status()


# ---------------------------------------------------------------------------
# App Registration
# ---------------------------------------------------------------------------


def ensure_app_registration(token: str, client_id_name: str) -> tuple[dict, str | None]:
    """Create the app registration if absent; configure service principal, API scope,
    access token version, redirect URI, client secret, and groups claim."""
    existing = get(token, f"/applications?$filter=displayName eq '{client_id_name}'")
    if existing["value"]:
        app = existing["value"][0]
        print(f"  [app] Already exists: {client_id_name} ({app['id']})")
    else:
        app = post(token, "/applications", {
            "displayName":            client_id_name,
            "signInAudience":         "AzureADMyOrg",
            "publicClient":           {"redirectUris": ["http://localhost"]},
            "isFallbackPublicClient": True,
        })
        print(f"  [app] Created: {client_id_name} ({app['id']})")
        time.sleep(10)  # Brief delay for propagation before configuring it further

    ensure_service_principal(token, app["appId"])
    configure_api_scope(token, app["id"], app["appId"])
    configure_redirect_uri(token, app["id"], ENTRA_REDIRECT_URI)
    configure_optional_claims(token, app["id"])
    configure_public_client_flow(token, app["id"], _PERSONA_CONFIG["client"]["public_client"])
    secret_value = ensure_client_secret(token, app["id"], ENTRA_SECRET_DISPLAY_NAME)
    return app, secret_value


def ensure_service_principal(token: str, app_client_id: str) -> dict:
    existing = get(token, f"/servicePrincipals?$filter=appId eq '{app_client_id}'")
    if existing["value"]:
        print("  [sp] Service principal already exists")
        return existing["value"][0]
    sp = post(token, "/servicePrincipals", {"appId": app_client_id})
    print(f"  [sp] Service principal created ({sp['id']})")
    return sp


def configure_api_scope(token: str, app_object_id: str, app_client_id: str) -> None:
    """
    Expose api://<client-id>/access so tokens have aud=api://<client-id>.

    Also sets requestedAccessTokenVersion=2, required for FastMCP's AzureProvider
    to validate tokens correctly (equivalent to the manual Manifest →
    api.requestedAccessTokenVersion portal step).
    """
    app = get(token, f"/applications/{app_object_id}")
    expected_uri = f"api://{app_client_id}"
    current_version = (app.get("api") or {}).get("requestedAccessTokenVersion")

    uri_ok = expected_uri in (app.get("identifierUris") or [])
    # Key off the scope's own presence, not the identifierUris side effect — otherwise a partial
    # re-run (URI already committed, scope missing for any reason) mints a fresh UUID every time.
    scope_ok = any(s.get("value") == "access" for s in (app.get("api") or {}).get("oauth2PermissionScopes") or [])
    version_ok = current_version == 2

    if uri_ok and scope_ok and version_ok:
        print(f"  [api] Scope already configured: {expected_uri}")
        print("  [api] Access token version already set to 2")
        return

    body: dict = {
        "identifierUris": [expected_uri],
        "api": {
            "requestedAccessTokenVersion": 2,
        },
    }
    if not scope_ok:
        body["api"]["oauth2PermissionScopes"] = [{
            "id":                      str(uuid.uuid4()),
            "adminConsentDescription": "Access KDB.AI",
            "adminConsentDisplayName": "Access KDB.AI",
            "isEnabled":               True,
            "type":                    "User",
            "value":                   "access",
        }]

    patch(token, f"/applications/{app_object_id}", body)
    print(f"  [api] Exposed API: {expected_uri}/access")
    print("  [api] Access token version set to 2")


def configure_redirect_uri(token: str, app_object_id: str, redirect_uri: str) -> None:
    """
    Add a Web platform redirect URI for the OAuth callback FastMCP's AzureProvider uses.
    Equivalent to the manual Authentication → Add a platform → Web portal step.
    """
    app = get(token, f"/applications/{app_object_id}")
    existing_uris = (app.get("web") or {}).get("redirectUris") or []

    if redirect_uri in existing_uris:
        print(f"  [redirect] Already configured: {redirect_uri}")
        return

    patch(token, f"/applications/{app_object_id}", {
        "web": {
            "redirectUris": existing_uris + [redirect_uri],
        },
    })
    print(f"  [redirect] Added: {redirect_uri}")


def ensure_client_secret(token: str, app_object_id: str, description: str) -> str | None:
    """
    Create a client secret for FastMCP's AzureProvider to use at runtime.

    Graph API only returns the secretText value once, at creation. If a secret with
    this display name already exists, a new one is NOT created (to avoid accumulating
    secrets on every run) and None is returned — the existing .env.entra value, if any,
    should be reused. To rotate, delete the existing secret in the portal first.
    """
    app = get(token, f"/applications/{app_object_id}")
    existing = [c for c in app.get("passwordCredentials", []) if c.get("displayName") == description]
    if existing:
        print(f"  [secret] Already exists: {description} (value not retrievable; reusing .env.entra)")
        return None

    cred = post(token, f"/applications/{app_object_id}/addPassword", {
        "passwordCredential": {"displayName": description}
    })
    print(f"  [secret] Created: {description}")
    return cred["secretText"]


def configure_public_client_flow(token: str, app_object_id: str, enabled: bool) -> None:
    """
    Enable ROPC (resource-owner password) sign-in on the app registration.

    Required for the password-flow token acquisition used by test personas
    (EntraTokenProvider's default `flow: password`) and by the manual ROPC
    curl in the summary output. Only set at app-creation time previously —
    idempotent here so it's also fixed up on an app registration that was
    created manually in the portal (the bootstrap path), where it defaults
    to disabled. Equivalent to the manual Authentication → Settings →
    "Allow public client flows" portal toggle.
    """
    app = get(token, f"/applications/{app_object_id}")
    if app.get("isFallbackPublicClient") == enabled:
        print(f"  [public-client] Already {'enabled' if enabled else 'disabled'}")
        return
    patch(token, f"/applications/{app_object_id}", {"isFallbackPublicClient": enabled})
    print(f"  [public-client] {'Enabled' if enabled else 'Disabled'} (ROPC sign-in)")


def configure_optional_claims(token: str, app_object_id: str) -> None:
    """Emit group Object IDs in access tokens."""
    app = get(token, f"/applications/{app_object_id}")
    groups_claim_present = any(
        c.get("name") == "groups"
        for c in (app.get("optionalClaims") or {}).get("accessToken") or []
    )
    if app.get("groupMembershipClaims") == "SecurityGroup" and groups_claim_present:
        print("  [claims] Groups claim already configured")
        return

    patch(token, f"/applications/{app_object_id}", {
        "groupMembershipClaims": "SecurityGroup",
        "optionalClaims": {
            "accessToken": [{"name": "groups", "essential": False, "additionalProperties": []}],
        },
    })
    print("  [claims] Groups claim configured in access token")


# ---------------------------------------------------------------------------
# Groups
# ---------------------------------------------------------------------------


def ensure_group(token: str, display_name: str) -> str:
    """Create security group if absent; return its Object ID."""
    existing = get(token, f"/groups?$filter=displayName eq '{display_name}'")
    if existing["value"]:
        print(f"    [group] Already exists: {display_name}")
        return existing["value"][0]["id"]
    g = post(token, "/groups", {
        "displayName":     display_name,
        "mailEnabled":     False,
        "mailNickname":    display_name.replace("-", ""),
        "securityEnabled": True,
        "description":     "kx-mcp-server real-IdP test group",
    })
    print(f"    [group] Created: {display_name} ({g['id']})")
    time.sleep(5)
    return g["id"]


# ---------------------------------------------------------------------------
# Users
# ---------------------------------------------------------------------------


def get_tenant_domain(token: str) -> str:
    # Use ENTRA_DOMAIN if already set — avoids requiring Organization.Read.All.
    if domain := os.environ.get("ENTRA_DOMAIN", "").strip():
        return domain
    org = get(token, "/organization")
    domains = org["value"][0]["verifiedDomains"]
    return next((d["name"] for d in domains if d.get("isDefault")), domains[0]["name"])


def _resolve_password(password_env: str) -> str:
    """Read the password from an env var; exit loudly if unset."""
    value = os.environ.get(password_env, "")
    if not value:
        print(f"ERROR: {password_env} is not set — set it before running this script.")
        print("  Passwords are never committed; inject them as env vars or masked CI variables.")
        sys.exit(1)
    return value


def ensure_user(token: str, username: str, password: str, domain: str) -> str:
    """Create a user if absent; return Object ID."""
    upn = f"{username}@{domain}"
    existing = get(token, f"/users?$filter=userPrincipalName eq '{upn}'")
    if existing["value"]:
        print(f"    [user] Already exists: {upn}")
        return existing["value"][0]["id"]
    u = post(token, "/users", {
        "displayName":       username,
        "userPrincipalName": upn,
        "mailNickname":      username,
        "accountEnabled":    True,
        "passwordProfile": {
            "password":                      password,
            "forceChangePasswordNextSignIn": False,
        },
    })
    print(f"    [user] Created: {upn} ({u['id']})")
    return u["id"]


def add_user_to_group(token: str, user_id: str, group_id: str, group_name: str,
                      retries: int = 5, delay: int = 3) -> None:
    """Add user to group; retry on 404 (Entra replication lag); skip if already a member."""
    for attempt in range(retries):
        try:
            post(token, f"/groups/{group_id}/members/$ref", {
                "@odata.id": f"{GRAPH_BASE}/directoryObjects/{user_id}"
            })
            print(f"      [membership] Added to {group_name}")
            return
        except requests.HTTPError as e:
            status = e.response.status_code
            if status == 404 and attempt < retries - 1:
                print(f"      [membership] Group not yet replicated, retrying in {delay}s... ({attempt + 1}/{retries})")
                time.sleep(delay)
            elif status == 400 and "already exist" in e.response.text.lower():
                print(f"      [membership] Already a member of {group_name}")
                return
            else:
                raise
    print(f"      [membership] ERROR: failed to add {user_id} to {group_name} after {retries} attempts")


# ---------------------------------------------------------------------------
# Token Lifetime Policy
# ---------------------------------------------------------------------------


def ensure_token_lifetime_policy(token: str, app_object_id: str, app_client_id: str,
                                  lifespan_seconds: int) -> None:
    """Attach a token lifetime policy to the service principal (requires Azure AD P1)."""
    minutes = max(lifespan_seconds // 60, 10)
    hours = minutes // 60
    remaining_mins = minutes % 60
    duration = f"{hours:02d}:{remaining_mins:02d}:00"

    try:
        sp = get(token, f"/servicePrincipals?$filter=appId eq '{app_client_id}'")
        if not sp["value"]:
            print("  [policy] SKIPPED — no service principal found")
            return
        sp_id = sp["value"][0]["id"]

        existing = get(token, f"/servicePrincipals/{sp_id}/tokenLifetimePolicies")
        if existing["value"]:
            print("  [policy] Token lifetime policy already attached")
            return

        policy = post(token, "/policies/tokenLifetimePolicies", {
            "definition": [json.dumps({
                "TokenLifetimePolicy": {"Version": 1, "AccessTokenLifetime": duration}
            })],
            "displayName":           f"kdbai-access-token-{minutes}min",
            "isOrganizationDefault": False,
        })
        post(token, f"/servicePrincipals/{sp_id}/tokenLifetimePolicies/$ref", {
            "@odata.id": f"{GRAPH_BASE}/policies/tokenLifetimePolicies/{policy['id']}"
        })
        print(f"  [policy] Token lifetime set to {duration}")

    except requests.HTTPError as e:
        if e.response.status_code == 403:
            print("  [policy] SKIPPED — requires Azure AD Premium P1 licence")
        else:
            print(f"  [policy] WARNING — failed ({e.response.status_code}): {e.response.text[:200]}")


# ---------------------------------------------------------------------------
# Output — write provisioned values to envs/.env.entra
# ---------------------------------------------------------------------------

# Repo root is 5 levels up from this file:
# tests/deterministic/realidp/setup/entra/entra_setup.py
_REPO_ROOT = Path(__file__).parents[5]
assert (_REPO_ROOT / "packages").is_dir(), (
    f"_REPO_ROOT resolved to {_REPO_ROOT}, which doesn't look like the repo root "
    "(no packages/ dir) — did entra_setup.py move relative to the repo root?"
)
_ENV_OUT = _REPO_ROOT / "tests" / "deterministic" / "realidp" / "envs" / ".env.entra"


def _read_existing_env_value(var_name: str) -> str:
    """
    Read a previously-written value for var_name from the existing .env.entra, if present.
    Used to preserve values (e.g. ENTRA_CLIENT_SECRET) across re-runs when this run did
    not regenerate them. Returns "" if the file or the variable doesn't exist yet.
    """
    if not _ENV_OUT.exists():
        return ""
    prefix = f"export {var_name}="
    for line in _ENV_OUT.read_text().splitlines():
        if line.startswith(prefix):
            value = line[len(prefix):].strip()
            # write_env_file always wraps values in double quotes — strip them back
            # off so re-writing this value doesn't double the quoting (or, for a
            # value left blank across successive runs, compound it indefinitely).
            if len(value) >= 2 and value[0] == '"' and value[-1] == '"':
                value = value[1:-1]
            return value
    return ""


def _get_preserved_value(var_name: str) -> str:
    """
    Return the value for var_name, preferring os.environ first (the operator's
    exported value on this run), then falling back to the existing .env.entra
    (a value written by a previous run).

    This ensures that:
    - A fresh first run with exported vars populates the output correctly.
    - A re-run with the same vars sourced from the existing .env.entra preserves them.
    - A re-run where the operator forgets to export a var doesn't blank it out.
    """
    return os.environ.get(var_name, "") or _read_existing_env_value(var_name)


def write_env_file(app_client_id: str, all_groups: dict, domain: str, secret_value: str | None) -> None:
    """Write the provisioned values to envs/.env.entra.

    The script reads inputs from the environment and writes the full live .env.entra.
    It does NOT copy .env.entra.example — that is a first-time-only README step.
    Re-running is safe: inputs are preserved from os.environ first, then the
    existing file (see _get_preserved_value).

    The client secret is only retrievable at creation time — it is written when
    freshly generated and preserved across re-runs from the existing file.
    User passwords are NEVER written; see _get_preserved_value.
    """
    tenant_id = ENTRA_CONFIG["tenant_id"]
    client_id = ENTRA_CONFIG["client_id"]
    app_id_uri = f"api://{app_client_id}"

    # Preserve secret from a prior run if this run didn't (re)generate it.
    secret_line = secret_value or _read_existing_env_value("ENTRA_CLIENT_SECRET")

    # Passwords: prefer os.environ (operator export), then existing file.
    password_root    = _get_preserved_value("ENTRA_PASSWORD_ROOT")
    password_alice   = _get_preserved_value("ENTRA_PASSWORD_ALICE")
    password_bob     = _get_preserved_value("ENTRA_PASSWORD_BOB")
    password_charlie = _get_preserved_value("ENTRA_PASSWORD_CHARLIE")
    tenant_id_risk   = _get_preserved_value("ENTRA_TENANT_ID_RISK")
    domain_risk      = _get_preserved_value("ENTRA_DOMAIN_RISK")

    lines = [
        "# Generated by tests/deterministic/realidp/setup/entra/entra_setup.py\n",
        "# Re-running the script is safe — inputs are preserved and Graph ops are idempotent.\n",
        "#\n",
        "# ENTRA_CLIENT_SECRET is only populated on the run that created it —\n",
        "# Graph API never returns an existing secret's value again. If blank, keep\n",
        "# your previously-saved value or rotate the secret in the portal.\n",
        "#\n",
        "# ENTRA_PASSWORD_* are NEVER written here — inject them as env vars or masked CI\n",
        "# variables before running. They are preserved across re-runs if already present.\n",
        "#\n",
        "# .env.entra is gitignored — do not commit it.\n",
        "# Run: just test-entra (sources this file automatically)\n",
        "\n",
        'export AUTH_PROVIDER="entra"\n',
        "\n",
        "# --- INPUTS (admin credentials) ---\n",
        f'export ENTRA_TENANT_ID="{tenant_id}"\n',
        f'export ENTRA_CLIENT_ID="{client_id}"\n',
        "\n",
        "# Client secret (auto-generated by this script; preserved across re-runs):\n",
        f'export ENTRA_CLIENT_SECRET="{secret_line or ""}"\n',
        "\n",
        "# --- INPUTS (per-user passwords — preserved if already set, never blank-overwritten) ---\n",
        f'export ENTRA_PASSWORD_ROOT="{password_root}"\n',
        f'export ENTRA_PASSWORD_ALICE="{password_alice}"\n',
        f'export ENTRA_PASSWORD_BOB="{password_bob}"\n',
        "\n",
        "# Second tenant — charlie wrong-issuer persona (test 2.41)\n",
        "# Set ENTRA_TENANT_ID_RISK, ENTRA_DOMAIN_RISK, ENTRA_PASSWORD_CHARLIE\n",
        "# to activate test_wrong_issuer_token_rejected under AUTH_PROVIDER=entra.\n",
        f'export ENTRA_TENANT_ID_RISK="{tenant_id_risk}"\n',
        f'export ENTRA_DOMAIN_RISK="{domain_risk}"\n',
        f'export ENTRA_PASSWORD_CHARLIE="{password_charlie}"\n',
        "\n",
        "# --- OUTPUTS (provisioned by this script) ---\n",
        f'export ENTRA_DOMAIN="{domain}"\n',
        f'export ENTRA_SCOPE="{app_id_uri}/access offline_access"\n',
        f'export ENTRA_APP_ID_URI="{app_id_uri}"\n',
        f'export ENTRA_REDIRECT_URI="{ENTRA_REDIRECT_URI}"\n',
        "\n",
        "# Group Object IDs:\n",
    ]
    for name, gid in sorted(all_groups.items()):
        env_var = "ENTRA_GROUP_" + name.upper().replace("-", "_")
        lines.append(f'export {env_var}="{gid}"\n')

    lines += [
        "\n",
        "# kdbai-db connection (kdbai ACL lane under Entra — just test-kdbai-entra).\n",
        "# Passthrough reuses this same ENTRA_CLIENT_ID audience for the KDB.AI hop\n",
        "# (single-audience model); see setup/entra/docker-compose.yaml + seed.py.\n",
        'export KDBAI_DB_HOST="127.0.0.1"\n',
        'export KDBAI_DB_PORT="8082"\n',
        'export KDBAI_DB_MODE="qipc"\n',
        "\n",
        "# ---------------------------------------------------------------------------\n",
        "# Container inbound validation — used by _spawn_container (just test-entra).\n",
        "#\n",
        "# IMPORTANT: confirm these by introspecting a real token before running tests:\n",
        "#   uv run kx auth introspect <token> --json\n",
        "#\n",
        "# This script sets requestedAccessTokenVersion=2, so tokens should be v2:\n",
        "#   iss = https://login.microsoftonline.com/<tid>/v2.0\n",
        "#   aud = <ENTRA_CLIENT_ID>  (bare GUID, NOT api://<id>)\n",
        "#\n",
        "# If your app was configured for v1 before this script ran:\n",
        "#   iss = https://sts.windows.net/<tid>/\n",
        "#   aud = api://<ENTRA_CLIENT_ID>\n",
        "# Uncomment and correct these lines to match the decoded token.\n",
        "# ---------------------------------------------------------------------------\n",
        # _spawn_container hardcodes KX_MCP_AUTH=jwks for the actual test-run subprocess
        # regardless of this file — this export exists so a manually-sourced .env.entra
        # is enough for `kx auth introspect` to pick jwks mode too (else it defaults to
        # 'unset' and reports "introspect requires KX_MCP_AUTH=static or jwks").
        'export KX_MCP_AUTH="jwks"\n',
        # v2 tokens (requestedAccessTokenVersion=2): aud = bare GUID, not api://<id>
        f'export KX_MCP_AUTH_AUDIENCE="{app_client_id}"\n',
        f'export KX_MCP_AUTH_ISSUER="https://login.microsoftonline.com/{tenant_id}/v2.0"\n',
        f'export KX_MCP_AUTH_JWKS_URI="https://login.microsoftonline.com/{tenant_id}/discovery/v2.0/keys"\n',
    ]

    _ENV_OUT.parent.mkdir(parents=True, exist_ok=True)
    with open(_ENV_OUT, "w") as f:
        f.writelines(lines)
    print(f"\n.env.entra written to {_ENV_OUT}")
    if secret_value:
        print("  ENTRA_CLIENT_SECRET was freshly generated this run and written.")
    elif secret_line:
        print("  ENTRA_CLIENT_SECRET preserved from the existing .env.entra (secret already existed).")
    else:
        print("  ENTRA_CLIENT_SECRET is blank — no existing value found and none generated.")
        print("  Fill it in manually or rotate the secret in the portal.")
    blank_passwords = [
        name for name, val in [
            ("ENTRA_PASSWORD_ROOT", password_root),
            ("ENTRA_PASSWORD_ALICE", password_alice),
            ("ENTRA_PASSWORD_BOB", password_bob),
        ] if not val
    ]
    if blank_passwords:
        print(f"  The following passwords are blank in .env.entra: {blank_passwords}")
        print("  Export them before running just test-entra.")


# ---------------------------------------------------------------------------
# Summary
# ---------------------------------------------------------------------------


def print_summary(app: dict, domain: str) -> None:
    tenant_id     = ENTRA_CONFIG["tenant_id"]
    app_client_id = app["appId"]
    print(f"""
Sample token acquisition (ROPC — confirm iss/aud by decoding the token at https://jwt.ms):

  curl -s -X POST \\
    "https://login.microsoftonline.com/{tenant_id}/oauth2/v2.0/token" \\
    -d "client_id={app_client_id}" \\
    -d "scope=api://{app_client_id}/access" \\
    -d "grant_type=password" \\
    -d "username=alice@{domain}" \\
    -d "password=<ENTRA_PASSWORD_ALICE>" \\
    | jq -r '.access_token' \\
    | uv run kx auth introspect - --json

Update KX_MCP_AUTH_ISSUER / KX_MCP_AUTH_AUDIENCE in .env.entra to match iss/aud above,
then run: just test-entra
""")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> None:
    print("Authenticating with Microsoft Graph...")
    token = get_access_token()

    domain = get_tenant_domain(token)
    print(f"Tenant domain: {domain}")
    print(f"Tenant ID:     {ENTRA_CONFIG['tenant_id']}\n")

    print("=== App Registration ===")
    app, secret_value = ensure_app_registration(token, _PERSONA_CONFIG["client"]["client_id"])

    # All namespaces share one app registration / service principal, so only one
    # token lifetime policy can ever be attached — set it once, up front, rather
    # than per-namespace (a per-namespace call would silently no-op for every
    # namespace after the first, since ensure_token_lifetime_policy's idempotency
    # check is "does a policy exist", not "does it match this namespace's value").
    # All namespaces currently configure the same lifespan; if that ever diverges,
    # this is the one value that wins.
    lifespan = next(iter(_PERSONA_CONFIG["namespaces"].values()))["token_settings"]["access_token_lifespan_seconds"]
    ensure_token_lifetime_policy(token, app["id"], app["appId"], lifespan)

    all_groups: dict[str, str] = {}
    for ns_name, ns_cfg in _PERSONA_CONFIG["namespaces"].items():
        print(f"\n=== Namespace: {ns_name} ===")

        group_ids: dict[str, str] = {}
        for group_name in ns_cfg["groups"]:
            full_name = f"{ns_name}-{group_name}"
            group_ids[group_name] = ensure_group(token, full_name)
            all_groups[full_name] = group_ids[group_name]

        for user_cfg in ns_cfg["users"]:
            # charlie belongs in the second tenant — skip in the primary tenant when
            # ENTRA_TENANT_ID_RISK is not configured. Scoped via second_tenant so a
            # merely-missing password for any other user fails loudly instead.
            if user_cfg.get("second_tenant") and not os.environ.get("ENTRA_TENANT_ID_RISK"):
                print(
                    f"    [user] Skipping {user_cfg['username']} — "
                    "second-tenant vars not set (ENTRA_TENANT_ID_RISK unset); "
                    "test 2.41 will be skipped at runtime."
                )
                continue
            password = _resolve_password(user_cfg["password_env"])
            uid = ensure_user(token, user_cfg["username"], password, domain)
            for g in user_cfg["groups"]:
                add_user_to_group(token, uid, group_ids[g], f"{ns_name}-{g}")

    write_env_file(app["appId"], all_groups, domain, secret_value)
    print_summary(app, domain)
    print("Done.")


if __name__ == "__main__":
    main()
